# Generated by Django 5.0.1 on 2024-03-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobilenumber', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=100)),
                ('eventname', models.CharField(max_length=100)),
            ],
        ),
    ]
