# Generated by Django 5.0.1 on 2024-03-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='mobilenumber',
            field=models.CharField(max_length=10),
        ),
    ]
