# Generated by Django 5.0.1 on 2024-03-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0002_alter_table_mobilenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='eventname',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='mobilenumber',
            new_name='mobile',
        ),
    ]
