# Generated by Django 5.0.1 on 2024-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0003_rename_eventname_table_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='mobile',
            field=models.CharField(max_length=100),
        ),
    ]
