# Generated by Django 5.0.1 on 2024-03-16 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0004_alter_table_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='event',
            new_name='eventname',
        ),
    ]
